/**
 * Copyright(c) Live2D Inc. All rights reserved.
 *
 * Use of this source code is governed by the Live2D Open Software license
 * that can be found at https://www.live2d.com/eula/live2d-open-software-license-agreement_en.html.
 */


#include "/Engine/Public/Platform.ush"

float4 Offset;

void MainVS(
	in float2 InPosition : ATTRIBUTE0, in float2 InUV : ATTRIBUTE1,
	out float4 OutPosition : SV_POSITION, out float2 OutUV : TEXCOORD0
)
{
	OutPosition = float4(InPosition.xy, 0.0, 1.0);

	OutPosition.xy += Offset.xy;
	OutPosition.xy *= Offset.z;

	// [0, 1] -> [-1, 1]
	OutPosition.xy = 2.0 * OutPosition.xy - 1.0;
	OutPosition.y *= -1.0;

	OutUV.x =       InUV.x;
	OutUV.y = 1.0 - InUV.y;
}

Texture2D MainTexture;
SamplerState MainSampler;
float4 Channel;

void MainPS(
	in float4 InPosition : SV_POSITION, in float2 InUV : TEXCOORD0,
	out float4 OutColor : SV_Target0
)
{
	float4 texColor = MainTexture.Sample(MainSampler, InUV);

	OutColor = Channel * texColor.a;
}
